### PR TITLE
digitize feature added

### PR DESCRIPTION
**Pull request by enricofer**
A cartographer ask me to add a button to instantprint dialor for digitizing the current rubberband map frame to the current active layer for easing the creation of touristic maps coverage.
Feel free to merge PR if you find the feature could have wide interest.

### CODE REVIEW

**Comment by manisandro** [comment]
So the goal is to have a persistent store of areas already printed?

**Comment by enricofer** [comment]
This could be, but the real aim of the user who asked me to modify the
plugin was to digitize many printing areas on a coverage layer to be used
as atlas context for printing. They draw touristic maps on ArcMap that can
draw on data frame the graphical objects on layout accordingly with target
scale. Now they want to migrate to QGIS and they don't find any similar
needed feature.

2017-07-17 11:46 GMT+02:00 Sandro Mani <notifications@github.com>:

**Comment by manisandro** [comment]
Ah so it's basically just "abusing" the print dialog to compute the rectangle which corresponds to a given scale?

**Comment by enricofer** [comment]
Yes it is. Tell me if you see a way to better generalize the feature.

2017-07-17 12:10 GMT+02:00 Sandro Mani <notifications@github.com>:

**Comment by manisandro** [comment]
So is there any relation at all with a print composer, or did you consider just extracting the necessary code to compute the extent based on paper size and scale and create a dedicated plugin for it?

**Comment by enricofer** [comment]
The typical workflow is composing a layout with a map at a fixed scale,
then on map canvas digitize the composer map extension in map units on a
coverage layer, and finally come back to composer to generate ad atlas with
the coverage layer as context. Now the cartographer user is happy with
custom istantPrint plugin. Writing a new plugin seem to me like reinventing
the wheel, and I can't imagine another use of the hack, so feel free to
keep the PR I provide you only if you find it has a wider field of
interest.

2017-07-17 13:21 GMT+02:00 Sandro Mani <notifications@github.com>:

**Comment by HusseinKabbout** [comment]
Closing this PR as it is obsolete.

**Pull request closed without merging**
