### PR TITLE
Map and rubberband rotation

### PR DESCRIPTION
**Pull request by tveinot**
I got stuck on the behaviour of the rubberband and reached out on the GIS Stack Exchange for some assistance. A member there made some edits that provided the ability to roate the map and rubber band accordingly. The member took a different approach than what I did so none of this code has anything in it that I did originally and I cannot take any credit. I am only posting it to share for those who were also looking for this feature. Using this approach I am working on adding it to the 2.X version of the plugin.

### CODE REVIEW

**Comment by HusseinKabbout** [comment]
It seems like you forgot to add some code to your commit. The changes in this pull request are only UI changes, which don't do much here. And also please add `__pycache__/` to your `.gitignore` file.

**Comment by pka** [comment]
Thanks for your contribution! Your PR does address #25, right?

**Comment by tveinot** [comment]
> Thanks for your contribution! Your PR does address #24, right?

Yes the selected layout respects the rotation applied to the rubberband; The drop down allows you to apply the roation to the map canvas in the layout or the map frame.

**Comment by tveinot** [comment]
image

**Comment by tveinot** [comment]
> It seems like you forgot to add some code to your commit. The changes in this pull request are only UI changes, which don't do much here. And also please add `__pycache__/` to your `.gitignore` file.

I don't know why this is, there was changes to the InstaPrintTool.py I tried to resubmit the files but it still says only the ui_printdialog.py has changed. This is my first "Pull Request" so it is a bit unfamiliar to me. Do you have an idea as to how I can fix this?

**Comment by tveinot** [comment]
> It seems like you forgot to add some code to your commit. The changes in this pull request are only UI changes, which don't do much here. And also please add `__pycache__/` to your `.gitignore` file.

Sorry, new to this... I added the missing files it should show 14 changes now instead of 5 and I think that was all.

**Comment by HusseinKabbout** [comment]
@tveinot Thanks, now I got everything I need to test your PR. But as I already mentioned in my first comment, please remove `__pycache__` from your repo.

**Comment by tveinot** [comment]
> @tveinot Thanks, now I got everything I need to test your PR. But as I already mentioned in my first comment, please remove `__pycache__` from your repo.

I think I got them all now

**Comment by HusseinKabbout** [comment]
@tveinot It seems that you are using `PyQt4` in this PR. The `qgis-instantprint-plugin` is a QGIS3 plugin and does not support `PyQt4` anymore. If you want this PR merged, then please rebase your branch to the current master and build your changes from there.

**Pull request closed without merging**
